---
- name: "create directory"
  file:
    path: /home/ubuntu/backend
    state: directory

- name: "save enviroment variables"
  become: true
  copy:
    src: /root/project/backend/.env
    dest: /home/ubuntu/backend/

- name: "copy package.json file"
  become: true
  copy:
    src: /root/project/backend/package.json
    dest: /home/ubuntu/backend/

- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
