---
- name: "copy files"
  become: true
  copy:
    src: /root/project/backend/backend.tar
    dest: /home/ubuntu/

- name: "un tar files"
  become: true
  shell: |
    tar -xvf backend.tar

- name: "install node dependencies"
  become: true
  shell: |
    npm i
  args:
    chdir: /home/ubuntu/backend

- name: "build"
  become: true
  shell: |
    npm run build
  args:
    chdir: /home/ubuntu/backend

- name: "pm2 start"
  become: true
  shell: |
    pm2 start npm --name backend -- start
  args:
    chdir: /home/ubuntu/backend
