---
- name: "copy files"
  become: true
  copy:
    src: /root/project/backend/backend.tar
    dest: /home/ubuntu/

- name: "create directory"
  file:
    path: /home/ubuntu/backend
    state: directory

- name: "un tar files"
  become: true
  shell: |
    tar -xvf backend.tar -C /home/ubuntu/backend

- name: "pm2 start"
  become: true
  shell: |
    pm2 start npm --name backend -- start
  args:
    chdir: /home/ubuntu/backend/backend
