---
- name: "copy files"
  become: true
  copy:
    src: /root/project/backend.tar
    dest: /home/ubuntu/

- name: "un tar files"
  become: true
  shell: |
    tar -xvf backend.tar -C /home/ubuntu

- name: "install node dependencies"
  become: true
  shell: |
    npm i
  args:
    chdir: /home/ubuntu/backend

- name: "build"
  become: true
  shell: |
    npm run build
  args:
    chdir: /home/ubuntu/backend

- name: "PM2 Start"
  become: true
  shell: |
    cd backend/
    pm2 start npm --name backend -- start
