---
- name: "copy files"
  become: true
  copy:
    src: /root/project/backend.tar
    dest: /home/ubuntu/

- name: "un tar files"
  become: true
  shell: |
    tar -xvf backend.tar -C /home/ubuntu/backend

- name: "start app"
  become: true
  shell: |
    npm i
    npm run build
    npm start
  args:
    chdir: /home/ubuntu/backend
